# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggest', models.TextField(max_length=200, verbose_name='意见')),
                ('suggest_time', models.DateTimeField(auto_now_add=True, verbose_name='提出时间')),
            ],
        ),
    ]
